import enum

class RequestType(enum.Enum):
    CONNECTION_CLOSED = 0
    SIGN_UP = 1
    SIGN_UP_CONFIRM = 2
    SIGN_IN = 11
    SIGN_IN_CONFIRM = 12
    INIT_MESSAGING = 21
    SEND_MESSAGE = 22
    RECEIVE_MESSAGES = 23

# 0-127: Good
# 128-255: Bad
class ResponseType(enum.Enum):
    CONNECTION_CLOSED = 0
    SIGN_UP_STARTED = 1
    SIGN_UP_SUCCESS = 2
    SIGN_IN_STARTED = 11
    SIGN_IN_SUCCESS = 12
    SENDING_REQUESTED_PUB_KEY = 21
    MESSAGE_SENT = 22
    SENDING_MESSAGE = 23
    REQUEST_TYPE_NOT_ALLOWED = 128
    PHONE_NUMBER_ALREADY_REGISTERED = 129
    SIGN_UP_WRONG_DIGITS = 130
    RECIPIENT_PHONE_NOT_EXIST = 131
    SIGN_UP_FAILED_INVALID_KEY = 151
    SIGN_IN_FAILED_PHONE_NUMBER_NOT_REGISTERED = 171
    SIGN_IN_FAILED_INVALID_SIGNATURE = 172
    UNKNOWN_REQUEST_TYPE = 255
